server:
  port: 80

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #同时注入两个注册中心

#设置OpenFeign客户端超时时间(OpenFeign默认支持ribbon)
ribbon:
#指的是建立连接所用的时问，适用于网络状况正常的情况下，两端连接所用的时问
  ConnectTimeout: 1000
#指的是建立连接后从服务提供方读取到可用资源所用的时间
  ReadTimeout: 3000
  #注意以上ribbon的超时配置好像不生效，需再次查证。

logging:
  level:
    #feign日志以什么级别监控哪个接口
    com.umbrella.leancloud.service.PaymentFeignService: debug
