server:
  port: 9527
spring:
  application:
    name: cloud-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #打开服务发现功能，从而从注册中心里读取注册列表
      routes:
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://cloud-payment-service #匹配微服务名进行路由
         # uri: http://localhost:8001
          predicates:
            - Path=/payment/get/**   #断言,路径相匹配的则进行路由

        - id: payment_routh2
          uri: lb://cloud-payment-service #匹配微服务名进行路由
         #uri: http://localhost:8001
          predicates:
            - Path=/payment/loadBalance/**   #断言,路径相匹配的则进行路由
            #- After=2020-03-08T10:59:34.102+08:00[Asia/Shanghai] #在某个时间之后才进行路由
            #- Before=2020-03-08T10:59:34.102+08:00[Asia/Shanghai] #在某个时间之前才进行路由
            #- Between=2020-03-08T10:59:34.102+08:00[Asia/Shanghai] ,  2020-03-08T10:59:34.102+08:00[Asia/Shanghai]
            #- Cookie=username,zhangshuai #请求中携带了Cookie，并且Cookie中有键值对username=zhangshuai的才能进行路由
            #- Header=X-Request-Id, \d+ #请求中携带了请求头，并且其中要有X-Request-Id属性，值为整数的  才能路由  （\d+为正则表达式）
            #- Host=**.atguigu.com  #请求中携带了主机名
            #- Method=GET #必须是get请求 才能路由
            #- Query=username, \d+ #请求中携带了参数，参数名称=username，值为正整数才能路由
          filters:
            - AddRequestHeader=X-Request-red, blue #过滤器链，代表在断言匹配的请求中，在该请求的请求头中加上一对名称为X-Request-red值为blue的k-v值，

eureka:
  instance:
    hostname: cloud-gateway
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka


